
version: '3'
services:
  repl-orquestrator-db:
    image: "postgres:latest"
    container_name: repl-orquestrator-db
    hostname: repl-orquestrator-db
    volumes:
      - repl-orquestrator-data:/var/lib/postgresql/data
#    ports:
#      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=123mudar


  repl-orquestrator-app:
    image: "kubeomatic/kafka-replicator-orchestrator:0.2"
    hostname: repl-orquestrator-app
    container_name: repl-orquestrator-app
    environment:
      - PSTGRES_URL=jdbc:postgresql://repl-orquestrator-db:5432/postgres
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=123mudar
      - POSTGRES_INIT=never
      - APP_CREDENTIALS=WyB7CiAgInVzZXJuYW1lIiA6ICJkYW1hdG8iLAogICJwYXNzd29yZCIgOiAie3NjcnlwdH0kZTA4MDEkMDM4NlBDY2dndUg2YVZDZGJOMk5ENjhFNXl4ci9iQ1JBdThvSklJcE8xSkhScTFsT3lCbksrLzR4VytPdndjd2c4dTM4TmhLbW5KaFgwZDdrNTdzQlE9PSQ0NEx4M0l5TDNYbGd3ZWZwQW16RGpjNWZHZC9wbnhMVGU5M01BK2NKeXJNPSIsCiAgImVuY29kZXIiIDogInNjcnlwdCIsCiAgInJvbGUiIDogImFkbWluIgp9LCB7CiAgInVzZXJuYW1lIiA6ICJydW5kZWNrIiwKICAicGFzc3dvcmQiIDogIntzY3J5cHR9JGUwODAxJHhSdnZNaW1mcHhZMTJYd2tiWEloVGIyOCtiV3VzeG5LSWNrcStxWmpLRmI0L0VINHNEcS93WFJ0bWVDNzJGS1kvZTVENThoN2pLSEI2cU5VbVRxaFVRPT0kRUhuZTNmbkxtLytreTR1SXJUbkRDV20xNkxGK3I4T0E0bjBLcnZwRVl4WT0iLAogICJlbmNvZGVyIiA6ICJzY3J5cHQiLAogICJyb2xlIiA6ICJhZG1pbiIKfSwgewogICJ1c2VybmFtZSIgOiAiZ3Vlc3QiLAogICJwYXNzd29yZCIgOiAie3NjcnlwdH0kZTA4MDEkdm8wKy81MEFBS3UzRk93VU0rS20vQWJJdzBWbDRGeE50M2RrQVh3WnZkTDZ4Q2l4TGo0eTlxNEVXUXNqM09Yc3BzODFPU1JjL3hiN29IL1VIVDRCVUE9PSRMZlZKZ21vTTdrYm5JSkJYMHRYWnBGbHA4dFBiRXJLQ0pYcEFLd2VrVnZrPSIsCiAgImVuY29kZXIiIDogInNjcnlwdCIsCiAgInJvbGUiIDogInZpZXciCn0gXQ==
    ports:
      - 8080:8080
    links:
      - repl-orquestrator-db
    depends_on:
      - repl-orquestrator-db
volumes:
  repl-orquestrator-data: